# Import thư viện, Khởi tạo và Metric

In [ ]:
import pandas as pd
import numpy as np
import os
import time
from sklearn.utils.class_weight import compute_class_weight

import gc
import rmm
import cudf
rmm.reinitialize(
    managed_memory=True,
)
import dask_cudf
import dask.array as da

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import (
    classification_report, accuracy_score, balanced_accuracy_score,
    f1_score, precision_score, recall_score, matthews_corrcoef,
    cohen_kappa_score, confusion_matrix
)

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

Using device: cuda

In [ ]:
import random
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed(42)

In [ ]:
class HybridDataset(Dataset):
    def __init__(self, X_seq, X_static, y):
        self.X_seq = torch.FloatTensor(X_seq)
        self.X_static = torch.FloatTensor(X_static)
        self.y = torch.LongTensor(y)

    def __len__(self):
        return len(self.y)

    def __getitem__(self, idx):
        return self.X_seq[idx], self.X_static[idx], self.y[idx]

class HybridBiLSTMModel(nn.Module):
    def __init__(self, input_dim_per_phase, static_dim):
        super().__init__()

        self.hidden_dim = 128
        self.num_layers = 1
        self.dropout_p = 0.3
        self.num_classes = 3

        self.bilstm = nn.LSTM(
            input_size=input_dim_per_phase,
            hidden_size=self.hidden_dim,
            num_layers=self.num_layers,
            batch_first=True,
            bidirectional=True
        )

        self.dropout = nn.Dropout(self.dropout_p)

        self.mlp = nn.Sequential(
            nn.Linear(static_dim, 64),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(64, 32),
            nn.ReLU()
        )

        self.fc = nn.Linear(self.hidden_dim * 2 + 32, self.num_classes)

    def forward(self, x_seq, x_static):
        _, (h_n, _) = self.bilstm(x_seq)

        # h_n: (num_layers*2, batch, hidden_dim)
        h_forward = h_n[-2]
        h_backward = h_n[-1]

        h_concat = torch.cat((h_forward, h_backward), dim=1)
        h_concat = self.dropout(h_concat)

        static_out = self.mlp(x_static)

        combined = torch.cat((h_concat, static_out), dim=1)
        return self.fc(combined)

In [ ]:
# Metrics
def gmean_score(y_true, y_pred):
    cm = confusion_matrix(y_true, y_pred)
    per_class = []
    for i in range(cm.shape[0]):
        tp = cm[i,i]
        fn = cm[i].sum() - tp
        fp = cm[:,i].sum() - tp
        tn = cm.sum() - tp - fn - fp
        sens = tp / (tp + fn) if (tp + fn) > 0 else 0
        spec = tn / (tn + fp) if (tn + fp) > 0 else 0
        per_class.append(np.sqrt(sens * spec))
    return np.prod(per_class) ** (1/len(per_class)) if per_class else 0

def gmean_per_class(y_true, y_pred, target_class):
    cm = confusion_matrix(y_true, y_pred)
    i = target_class
    tp = cm[i,i]
    fn = cm[i].sum() - tp
    fp = cm[:,i].sum() - tp
    tn = cm.sum() - tp - fn - fp

    recall = tp / (tp + fn) if (tp + fn) > 0 else 0
    specificity = tn / (tn + fp) if (tn + fp) > 0 else 0
    return np.sqrt(recall * specificity)

def print_results(
    version_name,
    phase,
    y_true,
    y_pred,
    time_build_model=None,
    time_predict=None
):
    target_names = ['Excellent', 'Good', 'Average']

    print(f"\n{'='*30} {version_name} - Phase {phase} {'='*30}")
    print(classification_report(
        y_true,
        y_pred,
        digits=10,
        target_names=target_names
    ))

    # Precision / Recall / F1 theo từng class
    prec_per_class = precision_score(y_true, y_pred, average=None)
    rec_per_class  = recall_score(y_true, y_pred, average=None)
    f1_per_class   = f1_score(y_true, y_pred, average=None)

    # G-Mean per class
    gmean_classes = [
        gmean_per_class(y_true, y_pred, i)
        for i in range(len(target_names))
    ]

    print("G-Mean per class (one-vs-rest):")
    for idx, name in enumerate(target_names):
        print(f"  {name:<10}: {gmean_classes[idx]:.10f}")

    print()

    # ===== TẠO DICTIONARY METRICS =====
    metrics = {
        'Version': version_name,
        'Phase': phase,

        'TimeBuildModel': time_build_model,
        'TimePredict': time_predict,

        'Accuracy': accuracy_score(y_true, y_pred),
        'BalancedAcc': balanced_accuracy_score(y_true, y_pred),

        'Precision Macro': precision_score(y_true, y_pred, average='macro'),
        'Precision Weighted': precision_score(y_true, y_pred, average='weighted'),

        'Recall Macro': recall_score(y_true, y_pred, average='macro'),
        'Recall Weighted': recall_score(y_true, y_pred, average='weighted'),

        'F1-Score Macro': f1_score(y_true, y_pred, average='macro'),
        'F1-Score Weighted': f1_score(y_true, y_pred, average='weighted'),

        'GMean': gmean_score(y_true, y_pred),

        'MCC': matthews_corrcoef(y_true, y_pred),
        'Kappa': cohen_kappa_score(y_true, y_pred),
    }

    # ===== THÊM METRIC CHO TỪNG CLASS =====
    for i, name in enumerate(target_names):
        metrics[f'Precision_{name}'] = prec_per_class[i]
        metrics[f'Recall_{name}'] = rec_per_class[i]
        metrics[f'F1-Score_{name}'] = f1_per_class[i]
        metrics[f'G-Mean_{name}'] = gmean_classes[i]

    # In ra console
    for k, v in metrics.items():
        if k not in ['Version', 'Phase'] and v is not None:
            print(f"{k:22} : {v:.10f}")

    return metrics

# Chuẩn bị dữ liệu + train

In [ ]:
def prepare_and_train_hybrid(train_path, val_path, device, version_name):

    print(f"Loading train (GPU): {train_path}")
    ddf_train = dask_cudf.read_parquet(train_path)

    df_val = pd.read_parquet(val_path, engine='pyarrow') if val_path else None

    train_len = len(ddf_train)
    print(f"Train samples: {train_len}")
    if df_val is not None:
        print(f"Validation samples: {len(df_val)}")

    cols_to_drop = ['user_id', 'course_id']
    ddf_train = ddf_train.drop(columns=[c for c in cols_to_drop if c in ddf_train.columns])

    if df_val is not None:
        df_val = df_val.drop(columns=cols_to_drop, errors='ignore')

    y_train = ddf_train['label_3'].compute().to_numpy()
    X_train_ddf = ddf_train.drop('label_3', axis=1)

    if df_val is not None:
        y_val = df_val['label_3'].values
        X_val_df = df_val.drop('label_3', axis=1)

    train_columns = X_train_ddf.columns.tolist()
    phase_cols = [c for c in train_columns if any(f"_p{p}_" in c for p in ['1','2','3','4'])]
    static_cols = [c for c in train_columns if c not in phase_cols]

    for p in ['1','2','3','4']:
        print(f"Phase {p}: {len([c for c in phase_cols if f'_p{p}_' in c])} features")

    def build_seq_dask(ddf, p_cols):
        phases = []
        for p in ['1','2','3','4']:
            cols = sorted([c for c in p_cols if f"_p{p}_" in c])
            phases.append(ddf[cols].compute().to_numpy())
        return np.stack(phases, axis=1)

    def build_seq_pandas(df, p_cols):
        phases = []
        for p in ['1','2','3','4']:
            cols = sorted([c for c in p_cols if f"_p{p}_" in c])
            phases.append(df[cols].values)
        return np.stack(phases, axis=1)

    X_seq_train = build_seq_dask(X_train_ddf, phase_cols)
    X_static_train = X_train_ddf[static_cols].compute().to_numpy()

    print(f"Time-series shape: {X_seq_train.shape}")
    print(f"Static feature shape: {X_static_train.shape}")

    scaler_seq = StandardScaler()
    N, T, F = X_seq_train.shape
    X_seq_train = scaler_seq.fit_transform(X_seq_train.reshape(-1, F)).reshape(N, T, F)

    scaler_static = StandardScaler()
    X_static_train = scaler_static.fit_transform(X_static_train)

    if df_val is not None:
        X_seq_val = build_seq_pandas(X_val_df, phase_cols)
        X_static_val = X_val_df[static_cols].values
        N2 = X_seq_val.shape[0]
        X_seq_val = scaler_seq.transform(X_seq_val.reshape(-1, F)).reshape(N2, T, F)
        X_static_val = scaler_static.transform(X_static_val)

    le = LabelEncoder()
    y_train_enc = le.fit_transform(y_train)
    print(f"Classes: {le.classes_}")

    if df_val is not None:
        y_val_enc = le.transform(y_val)

    train_loader = DataLoader(HybridDataset(X_seq_train, X_static_train, y_train_enc), batch_size=256, shuffle=True)

    if df_val is not None:
        val_loader = DataLoader(HybridDataset(X_seq_val, X_static_val, y_val_enc), batch_size=256, shuffle=False)

    model = HybridBiLSTMModel(F, X_static_train.shape[1]).to(device)

    unique_classes = np.unique(y_train_enc)
    weights = compute_class_weight('balanced', classes=unique_classes, y=y_train_enc)
    weights = torch.FloatTensor(weights).to(device)

    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001)

    best_loss = float('inf')
    patience = 10
    wait = 0
    start_train = time.perf_counter()

    for epoch in range(50):
        model.train()
        train_loss = 0
        for xb_seq, xb_static, yb in train_loader:
            xb_seq, xb_static, yb = xb_seq.to(device), xb_static.to(device), yb.to(device)
            optimizer.zero_grad()
            out = model(xb_seq, xb_static)
            loss = criterion(out, yb)
            loss.backward()
            optimizer.step()
            train_loss += loss.item()

        train_loss /= len(train_loader)

        if df_val is not None:
            model.eval()
            val_loss = 0
            with torch.no_grad():
                for xb_seq, xb_static, yb in val_loader:
                    xb_seq, xb_static, yb = xb_seq.to(device), xb_static.to(device), yb.to(device)
                    val_loss += criterion(model(xb_seq, xb_static), yb).item()
            val_loss /= len(val_loader)
            print(f"Epoch {epoch+1}: train = {train_loss:.4f}, val = {val_loss:.4f}")
            monitor = val_loss
        else:
            print(f"Epoch {epoch+1}: loss = {train_loss:.4f}")
            monitor = train_loss

        if monitor < best_loss - 1e-4:
            best_loss = monitor
            best_state = model.state_dict()
            wait = 0
        else:
            wait += 1
            if wait >= patience: break

    model.load_state_dict(best_state)
    time_build = time.perf_counter() - start_train

    os.makedirs("saved_models", exist_ok=True)
    torch.save(model.state_dict(), f"saved_models/BiLSTM_{version_name}.pt")

    return model, scaler_seq, scaler_static, le, phase_cols, static_cols, time_build

# Chạy theo từng V

In [ ]:
base_path = "/kaggle/input/datasets/anhtran10/lo-dataset"

In [ ]:
def run_experiment(base_path, train_file, val_file, test_prefix, version_name, device=None):
    if device is None:
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    print(f"\n{'#'*20}")
    print(f"Version: {version_name}")
    print(f"{'#'*20}")

    model, scaler_seq, scaler_static, le, phase_cols, static_cols, time_build = \
        prepare_and_train_hybrid(f"{base_path_1}/{train_file}", f"{base_path}/{val_file}", device, version_name)

    results = []

    model.eval()

    for phase in range(1, 5):
        test_path = f"{base_path}/{test_prefix}_{phase}.parquet"
        print(f"\n--- Test Phase {phase}: {test_path} ---")

        df = pd.read_parquet(test_path, engine='pyarrow')
        df = df.drop(columns=['user_id','course_id'], errors='ignore')

        y_test_raw = df['label_3'].values
        X_df = df.drop('label_3', axis=1)

        def build_seq_local(df_input):
            phases_list = []
            for p in ['1','2','3','4']:
                cols = sorted([c for c in phase_cols if f"_p{p}_" in c])
                phases_list.append(df_input[cols].values)
            return np.stack(phases_list, axis=1)

        X_seq_test = build_seq_local(X_df)
        X_static_test = X_df[static_cols].values

        N, T, F = X_seq_test.shape
        X_seq_test = scaler_seq.transform(X_seq_test.reshape(-1, F)).reshape(N, T, F)
        X_static_test = scaler_static.transform(X_static_test)

        y_test_enc = le.transform(y_test_raw)

        test_dataset = HybridDataset(X_seq_test, X_static_test, y_test_enc)
        test_loader = DataLoader(test_dataset, batch_size=256, shuffle=False)

        all_probs = []
        start_time = time.perf_counter()

        with torch.no_grad():
            for xb_seq, xb_static, _ in test_loader:
                xb_seq = xb_seq.to(device)
                xb_static = xb_static.to(device)

                outputs = model(xb_seq, xb_static)

                prob = torch.softmax(outputs, dim=1).cpu().numpy()
                all_probs.append(prob)

        time_pred = time.perf_counter() - start_time

        probs = np.vstack(all_probs)
        preds = np.argmax(probs, axis=1)

        metrics = print_results(version_name, phase, y_test_enc, preds, time_build, time_pred)

        os.makedirs("results_BiLSTM", exist_ok=True)

        cm = confusion_matrix(y_test_enc, preds)
        pd.DataFrame(cm).to_csv(f"results_BiLSTM/confusion_matrix_{version_name}_phase{phase}.csv", index=False)

        df_prob = pd.DataFrame(probs, columns=[f"Prob_Class_{i}" for i in range(probs.shape[1])])
        df_prob['y_true'] = y_test_enc
        df_prob['y_pred'] = preds
        df_prob.to_csv(f"results_BiLSTM/probability_matrix_{version_name}_phase{phase}.csv", index=False)

        results.append(metrics)

        del df, X_seq_test, X_static_test, all_probs, probs, preds
        torch.cuda.empty_cache()
        gc.collect()

    df_results = pd.DataFrame(results).round(10)

    ordered_cols = [
        "Version","Phase","TimeBuildModel","TimePredict","Accuracy","BalancedAcc",
        "Precision Macro","Precision Weighted","Recall Macro","Recall Weighted",
        "F1-Score Macro","F1-Score Weighted","GMean","MCC","Kappa",
        "Precision_Excellent","Recall_Excellent","F1-Score_Excellent","G-Mean_Excellent",
        "Precision_Good","Recall_Good","F1-Score_Good","G-Mean_Good",
        "Precision_Average","Recall_Average","F1-Score_Average","G-Mean_Average"
    ]

    df_results = df_results[[c for c in ordered_cols if c in df_results.columns]]

    return df_results

## V_Median

In [ ]:
base_path = "/kaggle/input/datasets/anhtran10/lo-dataset/Median/Median"

In [ ]:
df_v1 = run_experiment(
    base_path=base_path,
    train_file="train_median.parquet",
    val_file="val.parquet",
    test_prefix="test",
    version_name="V1 (Median)"
)
df_v1

####################
Version: V1 (Median)
####################
Loading train (GPU): /kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/train_median.parquet
Train samples: 1859619
Validation samples: 232452
Phase 1: 39 features
Phase 2: 39 features
Phase 3: 39 features
Phase 4: 39 features
Time-series shape: (1859619, 4, 39)
Static feature shape: (1859619, 23)
Classes: [0 1 2]
Epoch 1: train = 0.2472, val = 0.1451
Epoch 2: train = 0.1644, val = 0.1219
Epoch 3: train = 0.1393, val = 0.1123
Epoch 4: train = 0.1241, val = 0.1031
Epoch 5: train = 0.1201, val = 0.1209
Epoch 6: train = 0.1074, val = 0.1108
Epoch 7: train = 0.1029, val = 0.1181
Epoch 8: train = 0.0947, val = 0.1354
Epoch 9: train = 0.0911, val = 0.1298
Epoch 10: train = 0.0891, val = 0.1225
Epoch 11: train = 0.0862, val = 0.1295
Epoch 12: train = 0.0827, val = 0.1147
Epoch 13: train = 0.0814, val = 0.1405
Epoch 14: train = 0.0812, val = 0.1417

--- Test Phase 1: /kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/test_1.parquet ---

============================== V1 (Median) - Phase 1 ==============================
              precision    recall  f1-score   support

   Excellent  0.1505546751 0.4260089686 0.2224824356       223
        Good  0.0151427245 0.8628099174 0.0297630926       605
     Average  0.9996655688 0.8517388019 0.9197925287    231625

    accuracy                      0.8513591995    232453
   macro avg  0.3884543228 0.7135192293 0.3906793523    232453
weighted avg  0.9962885934 0.8513591995 0.9168071168    232453

G-Mean per class (one-vs-rest):
  Excellent : 0.6519399633
  Good      : 0.8581764447
  Average   : 0.8853511047

TimeBuildModel         : 593.2016220050
TimePredict            : 3.5953646590
Accuracy               : 0.8513591995
BalancedAcc            : 0.7135192293
Precision Macro        : 0.3884543228
Precision Weighted     : 0.9962885934
Recall Macro           : 0.7135192293
Recall Weighted        : 0.8513591995
F1-Score Macro         : 0.3906793523
F1-Score Weighted      : 0.9168071168
GMean                  : 0.7912248324
MCC                    : 0.1171091996
Kappa                  : 0.0325806287
Precision_Excellent    : 0.1505546751
Recall_Excellent       : 0.4260089686
F1-Score_Excellent     : 0.2224824356
G-Mean_Excellent       : 0.6519399633
Precision_Good         : 0.0151427245
Recall_Good            : 0.8628099174
F1-Score_Good          : 0.0297630926
G-Mean_Good            : 0.8581764447
Precision_Average      : 0.9996655688
Recall_Average         : 0.8517388019
F1-Score_Average       : 0.9197925287
G-Mean_Average         : 0.8853511047

--- Test Phase 2: /kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/test_2.parquet ---

============================== V1 (Median) - Phase 2 ==============================
              precision    recall  f1-score   support

   Excellent  0.0455891060 0.6905829596 0.0855317967       223
        Good  0.0141096335 0.8628099174 0.0277652190       605
     Average  0.9997709276 0.8290771722 0.9064582822    231625

    accuracy                      0.8290321054    232453
   macro avg  0.3531565557 0.7941566830 0.3399184326    232453
weighted avg  0.9962901911 0.8290321054 0.9033837858    232453

G-Mean per class (one-vs-rest):
  Excellent : 0.8252246618
  Good      : 0.8526862726
  Average   : 0.8860135050

TimeBuildModel         : 593.2016220050
TimePredict            : 3.5146747430
Accuracy               : 0.8290321054
BalancedAcc            : 0.7941566830
Precision Macro        : 0.3531565557
Precision Weighted     : 0.9962901911
Recall Macro           : 0.7941566830
Recall Weighted        : 0.8290321054
F1-Score Macro         : 0.3399184326
F1-Score Weighted      : 0.9033837858
GMean                  : 0.8542807176
MCC                    : 0.1149875591
Kappa                  : 0.0297045409
Precision_Excellent    : 0.0455891060
Recall_Excellent       : 0.6905829596
F1-Score_Excellent     : 0.0855317967
G-Mean_Excellent       : 0.8252246618
Precision_Good         : 0.0141096335
Recall_Good            : 0.8628099174
F1-Score_Good          : 0.0277652190
G-Mean_Good            : 0.8526862726
Precision_Average      : 0.9997709276
Recall_Average         : 0.8290771722
F1-Score_Average       : 0.9064582822
G-Mean_Average         : 0.8860135050

--- Test Phase 3: /kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/test_3.parquet ---

============================== V1 (Median) - Phase 3 ==============================
              precision    recall  f1-score   support

   Excellent  0.0387658228 0.8789237668 0.0742564880       223
        Good  0.0176650328 0.9173553719 0.0346625863       605
     Average  0.9998877431 0.8460097140 0.9165349248    231625

    accuracy                      0.8462269792    232453
   macro avg  0.3521061995 0.8807629509 0.3418179997    232453
weighted avg  0.9964092983 0.8462269792 0.9134316702    232453

G-Mean per class (one-vs-rest):
  Excellent : 0.9276475971
  Good      : 0.8917619759
  Average   : 0.9074861955

TimeBuildModel         : 593.2016220050
TimePredict            : 3.5185766120
Accuracy               : 0.8462269792
BalancedAcc            : 0.8807629509
Precision Macro        : 0.3521061995
Precision Weighted     : 0.9964092983
Recall Macro           : 0.8807629509
Recall Weighted        : 0.8462269792
F1-Score Macro         : 0.3418179997
F1-Score Weighted      : 0.9134316702
GMean                  : 0.9088467682
MCC                    : 0.1315614300
Kappa                  : 0.0361451097
Precision_Excellent    : 0.0387658228
Recall_Excellent       : 0.8789237668
F1-Score_Excellent     : 0.0742564880
G-Mean_Excellent       : 0.9276475971
Precision_Good         : 0.0176650328
Recall_Good            : 0.9173553719
F1-Score_Good          : 0.0346625863
G-Mean_Good            : 0.8917619759
Precision_Average      : 0.9998877431
Recall_Average         : 0.8460097140
F1-Score_Average       : 0.9165349248
G-Mean_Average         : 0.9074861955

--- Test Phase 4: /kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/test_4.parquet ---

============================== V1 (Median) - Phase 4 ==============================
              precision    recall  f1-score   support

   Excellent  0.2509270705 0.9103139013 0.3934108527       223
        Good  0.3403361345 0.9371900826 0.4993394980       605
     Average  0.9998912939 0.9927814355 0.9963236807    231625

    accuracy                      0.9925576353    232453
   macro avg  0.5303848330 0.9467618065 0.6296913438    232453
weighted avg  0.9974561785 0.9925576353 0.9944517970    232453

G-Mean per class (one-vs-rest):
  Excellent : 0.9528580448
  Good      : 0.9657886094
  Average   : 0.9812268599

TimeBuildModel         : 593.2016220050
TimePredict            : 3.5129737860
Accuracy               : 0.9925576353
BalancedAcc            : 0.9467618065
Precision Macro        : 0.5303848330
Precision Weighted     : 0.9974561785
Recall Macro           : 0.9467618065
Recall Weighted        : 0.9925576353
F1-Score Macro         : 0.6296913438
F1-Score Weighted      : 0.9944517970
GMean                  : 0.9665549975
MCC                    : 0.5476037143
Kappa                  : 0.4740157493
Precision_Excellent    : 0.2509270705
Recall_Excellent       : 0.9103139013
F1-Score_Excellent     : 0.3934108527
G-Mean_Excellent       : 0.9528580448
Precision_Good         : 0.3403361345
Recall_Good            : 0.9371900826
F1-Score_Good          : 0.4993394980
G-Mean_Good            : 0.9657886094
Precision_Average      : 0.9998912939
Recall_Average         : 0.9927814355
F1-Score_Average       : 0.9963236807
G-Mean_Average         : 0.9812268599

,Version,Phase,TimeBuildModel,TimePredict,Accuracy,BalancedAcc,Precision Macro,Precision Weighted,Recall Macro,Recall Weighted,F1-Score Macro,F1-Score Weighted,GMean,MCC,Kappa,Precision_Excellent,Recall_Excellent,F1-Score_Excellent,G-Mean_Excellent,Precision_Good,Recall_Good,F1-Score_Good,G-Mean_Good,Precision_Average,Recall_Average,F1-Score_Average,G-Mean_Average
0,V1 (Median),1,593.201622,3.595365,0.851359,0.713519,0.388454,0.996289,0.713519,0.851359,0.390679,0.916807,0.791225,0.117109,0.032581,0.150555,0.426009,0.222482,0.651940,0.015143,0.862810,0.029763,0.858176,0.999666,0.851739,0.919793,0.885351
1,V1 (Median),2,593.201622,3.514675,0.829032,0.794157,0.353157,0.996290,0.794157,0.829032,0.339918,0.903384,0.854281,0.114988,0.029705,0.045589,0.690583,0.085532,0.825225,0.014110,0.862810,0.027765,0.852686,0.999771,0.829077,0.906458,0.886014
2,V1 (Median),3,593.201622,3.518577,0.846227,0.880763,0.352106,0.996409,0.880763,0.846227,0.341818,0.913432,0.908847,0.131561,0.036145,0.038766,0.878924,0.074256,0.927648,0.017665,0.917355,0.034663,0.891762,0.999888,0.846010,0.916535,0.907486
3,V1 (Median),4,593.201622,3.512974,0.992558,0.946762,0.530385,0.997456,0.946762,0.992558,0.629691,0.994452,0.966555,0.547604,0.474016,0.250927,0.910314,0.393411,0.952858,0.340336,0.937190,0.499339,0.965789,0.999891,0.992781,0.996324,0.981227

In [ ]:
df_v1.to_csv("results_v1.csv", index=False)

## V_SMOTE

In [ ]:
base_path_1 = "/kaggle/input/datasets/uyentran10/lo-smote-test"

In [ ]:
base_path = "/kaggle/input/datasets/anhtran10/lo-dataset/Median/Median"

In [ ]:
df_v22 = run_experiment(
    base_path=base_path,
    train_file="train_median_smote.parquet",
    val_file="val.parquet",
    test_prefix="test",
    version_name="V22 (Median SMOTE)"
)
df_v22

####################
Version: V22 (Median SMOTE)
####################
Loading train (GPU): /kaggle/input/datasets/uyentran10/lo-smote-test/train_median_smote.parquet
Train samples: 5558991
Validation samples: 232452
Phase 1: 39 features
Phase 2: 39 features
Phase 3: 39 features
Phase 4: 39 features
Time-series shape: (5558991, 4, 39)
Static feature shape: (5558991, 23)
Classes: [0 1 2]
Epoch 1: train = 0.0473, val = 0.0311
Epoch 2: train = 0.0231, val = 0.0257
Epoch 3: train = 0.0190, val = 0.0284
Epoch 4: train = 0.0172, val = 0.0238
Epoch 5: train = 0.0159, val = 0.0255
Epoch 6: train = 0.0149, val = 0.0258
Epoch 7: train = 0.0141, val = 0.0267
Epoch 8: train = 0.0137, val = 0.0250
Epoch 9: train = 0.0132, val = 0.0284
Epoch 10: train = 0.0129, val = 0.0240
Epoch 11: train = 0.0125, val = 0.0252
Epoch 12: train = 0.0123, val = 0.0251
Epoch 13: train = 0.0120, val = 0.0275
Epoch 14: train = 0.0118, val = 0.0243

--- Test Phase 1: /kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/test_1.parquet ---

============================== V22 (Median SMOTE) - Phase 1 ==============================
              precision    recall  f1-score   support

   Excellent  0.1619565217 0.6681614350 0.2607174103       223
        Good  0.3445378151 0.0677685950 0.1132596685       605
     Average  0.9975195969 0.9966109012 0.9970650420    231625

    accuracy                      0.9938783324    232453
   macro avg  0.5013379779 0.5775136438 0.4570140403    232453
weighted avg  0.9950185126 0.9938783324 0.9940583793    232453

G-Mean per class (one-vs-rest):
  Excellent : 0.8160533986
  Good      : 0.2602802256
  Average   : 0.5529228101

TimeBuildModel         : 1718.2355358000
TimePredict            : 3.2897168120
Accuracy               : 0.9938783324
BalancedAcc            : 0.5775136438
Precision Macro        : 0.5013379779
Precision Weighted     : 0.9950185126
Recall Macro           : 0.5775136438
Recall Weighted        : 0.9938783324
F1-Score Macro         : 0.4570140403
F1-Score Weighted      : 0.9940583793
GMean                  : 0.4897127594
MCC                    : 0.2375271518
Kappa                  : 0.2358118094
Precision_Excellent    : 0.1619565217
Recall_Excellent       : 0.6681614350
F1-Score_Excellent     : 0.2607174103
G-Mean_Excellent       : 0.8160533986
Precision_Good         : 0.3445378151
Recall_Good            : 0.0677685950
F1-Score_Good          : 0.1132596685
G-Mean_Good            : 0.2602802256
Precision_Average      : 0.9975195969
Recall_Average         : 0.9966109012
F1-Score_Average       : 0.9970650420
G-Mean_Average         : 0.5529228101

--- Test Phase 2: /kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/test_2.parquet ---

============================== V22 (Median SMOTE) - Phase 2 ==============================
              precision    recall  f1-score   support

   Excellent  0.3611793612 0.6591928251 0.4666666667       223
        Good  0.4898785425 0.2000000000 0.2840375587       605
     Average  0.9977178504 0.9984673502 0.9980924596    231625

    accuracy                      0.9960637204    232453
   macro avg  0.6162585847 0.6192200585 0.5829322283    232453
weighted avg  0.9957854560 0.9960637204 0.9957241909    232453

G-Mean per class (one-vs-rest):
  Excellent : 0.8114522821
  Good      : 0.4470920577
  Average   : 0.6004645321

TimeBuildModel         : 1718.2355358000
TimePredict            : 3.5215242560
Accuracy               : 0.9960637204
BalancedAcc            : 0.6192200585
Precision Macro        : 0.6162585847
Precision Weighted     : 0.9957854560
Recall Macro           : 0.6192200585
Recall Weighted        : 0.9960637204
F1-Score Macro         : 0.5829322283
F1-Score Weighted      : 0.9957241909
GMean                  : 0.6017033558
MCC                    : 0.3839331112
Kappa                  : 0.3811869199
Precision_Excellent    : 0.3611793612
Recall_Excellent       : 0.6591928251
F1-Score_Excellent     : 0.4666666667
G-Mean_Excellent       : 0.8114522821
Precision_Good         : 0.4898785425
Recall_Good            : 0.2000000000
F1-Score_Good          : 0.2840375587
G-Mean_Good            : 0.4470920577
Precision_Average      : 0.9977178504
Recall_Average         : 0.9984673502
F1-Score_Average       : 0.9980924596
G-Mean_Average         : 0.6004645321

--- Test Phase 3: /kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/test_3.parquet ---

============================== V22 (Median SMOTE) - Phase 3 ==============================
              precision    recall  f1-score   support

   Excellent  0.3760330579 0.8161434978 0.5148514851       223
        Good  0.5773672055 0.4132231405 0.4816955684       605
     Average  0.9984149333 0.9980313006 0.9982230801    231625

    accuracy                      0.9963347429    232453
   macro avg  0.6506050656 0.7424659796 0.6649233779    232453
weighted avg  0.9967220103 0.9963347429 0.9964150113    232453

G-Mean per class (one-vs-rest):
  Excellent : 0.9028190053
  Good      : 0.6425706025
  Average   : 0.7454308724

TimeBuildModel         : 1718.2355358000
TimePredict            : 3.4771249220
Accuracy               : 0.9963347429
BalancedAcc            : 0.7424659796
Precision Macro        : 0.6506050656
Precision Weighted     : 0.9967220103
Recall Macro           : 0.7424659796
Recall Weighted        : 0.9963347429
F1-Score Macro         : 0.6649233779
F1-Score Weighted      : 0.9964150113
GMean                  : 0.7562109708
MCC                    : 0.5111154318
Kappa                  : 0.5103848860
Precision_Excellent    : 0.3760330579
Recall_Excellent       : 0.8161434978
F1-Score_Excellent     : 0.5148514851
G-Mean_Excellent       : 0.9028190053
Precision_Good         : 0.5773672055
Recall_Good            : 0.4132231405
F1-Score_Good          : 0.4816955684
G-Mean_Good            : 0.6425706025
Precision_Average      : 0.9984149333
Recall_Average         : 0.9980313006
F1-Score_Average       : 0.9982230801
G-Mean_Average         : 0.7454308724

--- Test Phase 4: /kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/test_4.parquet ---

============================== V22 (Median SMOTE) - Phase 4 ==============================
              precision    recall  f1-score   support

   Excellent  0.3527336861 0.8968609865 0.5063291139       223
        Good  0.4015025042 0.7950413223 0.5335551858       605
     Average  0.9995275003 0.9954840799 0.9975016926    231625

    accuracy                      0.9948677797    232453
   macro avg  0.5845878969 0.8957954629 0.6791286641    232453
weighted avg  0.9973505435 0.9948677797 0.9958229914    232453

G-Mean per class (one-vs-rest):
  Excellent : 0.9462788439
  Good      : 0.8902710950
  Average   : 0.9297505337

TimeBuildModel         : 1718.2355358000
TimePredict            : 3.4764376790
Accuracy               : 0.9948677797
BalancedAcc            : 0.8957954629
Precision Macro        : 0.5845878969
Precision Weighted     : 0.9973505435
Recall Macro           : 0.8957954629
Recall Weighted        : 0.9948677797
F1-Score Macro         : 0.6791286641
F1-Score Weighted      : 0.9958229914
GMean                  : 0.9217983930
MCC                    : 0.5774687951
Kappa                  : 0.5381430903
Precision_Excellent    : 0.3527336861
Recall_Excellent       : 0.8968609865
F1-Score_Excellent     : 0.5063291139
G-Mean_Excellent       : 0.9462788439
Precision_Good         : 0.4015025042
Recall_Good            : 0.7950413223
F1-Score_Good          : 0.5335551858
G-Mean_Good            : 0.8902710950
Precision_Average      : 0.9995275003
Recall_Average         : 0.9954840799
F1-Score_Average       : 0.9975016926
G-Mean_Average         : 0.9297505337

,Version,Phase,TimeBuildModel,TimePredict,Accuracy,BalancedAcc,Precision Macro,Precision Weighted,Recall Macro,Recall Weighted,F1-Score Macro,F1-Score Weighted,GMean,MCC,Kappa,Precision_Excellent,Recall_Excellent,F1-Score_Excellent,G-Mean_Excellent,Precision_Good,Recall_Good,F1-Score_Good,G-Mean_Good,Precision_Average,Recall_Average,F1-Score_Average,G-Mean_Average
0,V22 (Median SMOTE),1,1718.235536,3.289717,0.993878,0.577514,0.501338,0.995019,0.577514,0.993878,0.457014,0.994058,0.489713,0.237527,0.235812,0.161957,0.668161,0.260717,0.816053,0.344538,0.067769,0.113260,0.260280,0.997520,0.996611,0.997065,0.552923
1,V22 (Median SMOTE),2,1718.235536,3.521524,0.996064,0.619220,0.616259,0.995785,0.619220,0.996064,0.582932,0.995724,0.601703,0.383933,0.381187,0.361179,0.659193,0.466667,0.811452,0.489879,0.200000,0.284038,0.447092,0.997718,0.998467,0.998092,0.600465
2,V22 (Median SMOTE),3,1718.235536,3.477125,0.996335,0.742466,0.650605,0.996722,0.742466,0.996335,0.664923,0.996415,0.756211,0.511115,0.510385,0.376033,0.816143,0.514851,0.902819,0.577367,0.413223,0.481696,0.642571,0.998415,0.998031,0.998223,0.745431
3,V22 (Median SMOTE),4,1718.235536,3.476438,0.994868,0.895795,0.584588,0.997351,0.895795,0.994868,0.679129,0.995823,0.921798,0.577469,0.538143,0.352734,0.896861,0.506329,0.946279,0.401503,0.795041,0.533555,0.890271,0.999528,0.995484,0.997502,0.929751

In [ ]:
df_v22.to_csv("results_v22.csv", index=False)

## V_GAN

In [ ]:
base_path_1 = "/kaggle/input/datasets/anhtran10/lo-gan-test"

In [ ]:
df_v23 = run_experiment(
    base_path=base_path,
    train_file="train_median_gan.parquet",
    val_file="val.parquet",
    test_prefix="test",
    version_name="V23 (Median GAN)"
)

df_v23

####################
Version: V23 (Median GAN)
####################
Loading train (GPU): /kaggle/input/datasets/anhtran10/lo-gan-test/train_median_gan.parquet
Train samples: 5558991
Validation samples: 232452
Phase 1: 39 features
Phase 2: 39 features
Phase 3: 39 features
Phase 4: 39 features
Time-series shape: (5558991, 4, 39)
Static feature shape: (5558991, 23)
Classes: [0 1 2]
Epoch 1: train = 0.0034, val = 0.0060
Epoch 2: train = 0.0021, val = 0.0052
Epoch 3: train = 0.0019, val = 0.0055
Epoch 4: train = 0.0018, val = 0.0050
Epoch 5: train = 0.0017, val = 0.0050
Epoch 6: train = 0.0017, val = 0.0050
Epoch 7: train = 0.0016, val = 0.0051
Epoch 8: train = 0.0015, val = 0.0049
Epoch 9: train = 0.0015, val = 0.0050
Epoch 10: train = 0.0015, val = 0.0050
Epoch 11: train = 0.0014, val = 0.0052
Epoch 12: train = 0.0014, val = 0.0050
Epoch 13: train = 0.0014, val = 0.0052
Epoch 14: train = 0.0013, val = 0.0051

--- Test Phase 1: /kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/test_1.parquet ---

============================== V23 (Median GAN) - Phase 1 ==============================
              precision    recall  f1-score   support

   Excellent  0.9333333333 0.0627802691 0.1176470588       223
        Good  0.3150000000 0.2082644628 0.2507462687       605
     Average  0.9972289022 0.9990070157 0.9981171670    231625

    accuracy                      0.9960508146    232453
   macro avg  0.7485207452 0.4233505825 0.4555034982    232453
weighted avg  0.9953919837 0.9960508146 0.9953273375    232453

G-Mean per class (one-vs-rest):
  Excellent : 0.2505593717
  Good      : 0.4560902696
  Average   : 0.4724490335

TimeBuildModel         : 1730.6136856430
TimePredict            : 3.5485523720
Accuracy               : 0.9960508146
BalancedAcc            : 0.4233505825
Precision Macro        : 0.7485207452
Precision Weighted     : 0.9953919837
Recall Macro           : 0.4233505825
Recall Weighted        : 0.9960508146
F1-Score Macro         : 0.4555034982
F1-Score Weighted      : 0.9953273375
GMean                  : 0.3779538797
MCC                    : 0.2756841383
Kappa                  : 0.2599557148
Precision_Excellent    : 0.9333333333
Recall_Excellent       : 0.0627802691
F1-Score_Excellent     : 0.1176470588
G-Mean_Excellent       : 0.2505593717
Precision_Good         : 0.3150000000
Recall_Good            : 0.2082644628
F1-Score_Good          : 0.2507462687
G-Mean_Good            : 0.4560902696
Precision_Average      : 0.9972289022
Recall_Average         : 0.9990070157
F1-Score_Average       : 0.9981171670
G-Mean_Average         : 0.4724490335

--- Test Phase 2: /kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/test_2.parquet ---

============================== V23 (Median GAN) - Phase 2 ==============================
              precision    recall  f1-score   support

   Excellent  0.9565217391 0.0986547085 0.1788617886       223
        Good  0.4805970149 0.2661157025 0.3425531915       605
     Average  0.9975311834 0.9995553157 0.9985422238    231625

    accuracy                      0.9967821452    232453
   macro avg  0.8115499791 0.4547752422 0.5066524013    232453
weighted avg  0.9961464291 0.9967821452 0.9960485493    232453

G-Mean per class (one-vs-rest):
  Excellent : 0.3140927947
  Good      : 0.5156704227
  Average   : 0.5548279595

TimeBuildModel         : 1730.6136856430
TimePredict            : 3.5059484640
Accuracy               : 0.9967821452
BalancedAcc            : 0.4547752422
Precision Macro        : 0.8115499791
Precision Weighted     : 0.9961464291
Recall Macro           : 0.4547752422
Recall Weighted        : 0.9967821452
F1-Score Macro         : 0.5066524013
F1-Score Weighted      : 0.9960485493
GMean                  : 0.4479155895
MCC                    : 0.4011141559
Kappa                  : 0.3681529697
Precision_Excellent    : 0.9565217391
Recall_Excellent       : 0.0986547085
F1-Score_Excellent     : 0.1788617886
G-Mean_Excellent       : 0.3140927947
Precision_Good         : 0.4805970149
Recall_Good            : 0.2661157025
F1-Score_Good          : 0.3425531915
G-Mean_Good            : 0.5156704227
Precision_Average      : 0.9975311834
Recall_Average         : 0.9995553157
F1-Score_Average       : 0.9985422238
G-Mean_Average         : 0.5548279595

--- Test Phase 3: /kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/test_3.parquet ---

============================== V23 (Median GAN) - Phase 3 ==============================
              precision    recall  f1-score   support

   Excellent  0.9821428571 0.2466367713 0.3942652330       223
        Good  0.3631090487 0.5173553719 0.4267211997       605
     Average  0.9985229015 0.9981349164 0.9983288712    231625

    accuracy                      0.9961626651    232453
   macro avg  0.7812582691 0.5873756865 0.6064384346    232453
weighted avg  0.9968534108 0.9961626651 0.9962616627    232453

G-Mean per class (one-vs-rest):
  Excellent : 0.4966243140
  Good      : 0.7184220975
  Average   : 0.7654160952

TimeBuildModel         : 1730.6136856430
TimePredict            : 3.4958127670
Accuracy               : 0.9961626651
BalancedAcc            : 0.5873756865
Precision Macro        : 0.7812582691
Precision Weighted     : 0.9968534108
Recall Macro           : 0.5873756865
Recall Weighted        : 0.9961626651
F1-Score Macro         : 0.6064384346
F1-Score Weighted      : 0.9962616627
GMean                  : 0.6487864189
MCC                    : 0.4881834687
Kappa                  : 0.4874838160
Precision_Excellent    : 0.9821428571
Recall_Excellent       : 0.2466367713
F1-Score_Excellent     : 0.3942652330
G-Mean_Excellent       : 0.4966243140
Precision_Good         : 0.3631090487
Recall_Good            : 0.5173553719
F1-Score_Good          : 0.4267211997
G-Mean_Good            : 0.7184220975
Precision_Average      : 0.9985229015
Recall_Average         : 0.9981349164
F1-Score_Average       : 0.9983288712
G-Mean_Average         : 0.7654160952

--- Test Phase 4: /kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/test_4.parquet ---

============================== V23 (Median GAN) - Phase 4 ==============================
              precision    recall  f1-score   support

   Excellent  0.8785046729 0.8430493274 0.8604118993       223
        Good  0.7895833333 0.6264462810 0.6986175115       605
     Average  0.9990291639 0.9996071236 0.9993180602    231625

    accuracy                      0.9984857154    232453
   macro avg  0.8890390567 0.8230342440 0.8527824903    232453
weighted avg  0.9983684209 0.9984857154 0.9984021765    232453

G-Mean per class (one-vs-rest):
  Excellent : 0.9181257764
  Good      : 0.7913111790
  Average   : 0.8532143652

TimeBuildModel         : 1730.6136856430
TimePredict            : 3.4930247080
Accuracy               : 0.9984857154
BalancedAcc            : 0.8230342440
Precision Macro        : 0.8890390567
Precision Weighted     : 0.9983684209
Recall Macro           : 0.8230342440
Recall Weighted        : 0.9984857154
F1-Score Macro         : 0.8527824903
F1-Score Weighted      : 0.9984021765
GMean                  : 0.8526468923
MCC                    : 0.7711409744
Kappa                  : 0.7681271511
Precision_Excellent    : 0.8785046729
Recall_Excellent       : 0.8430493274
F1-Score_Excellent     : 0.8604118993
G-Mean_Excellent       : 0.9181257764
Precision_Good         : 0.7895833333
Recall_Good            : 0.6264462810
F1-Score_Good          : 0.6986175115
G-Mean_Good            : 0.7913111790
Precision_Average      : 0.9990291639
Recall_Average         : 0.9996071236
F1-Score_Average       : 0.9993180602
G-Mean_Average         : 0.8532143652

,Version,Phase,TimeBuildModel,TimePredict,Accuracy,BalancedAcc,Precision Macro,Precision Weighted,Recall Macro,Recall Weighted,F1-Score Macro,F1-Score Weighted,GMean,MCC,Kappa,Precision_Excellent,Recall_Excellent,F1-Score_Excellent,G-Mean_Excellent,Precision_Good,Recall_Good,F1-Score_Good,G-Mean_Good,Precision_Average,Recall_Average,F1-Score_Average,G-Mean_Average
0,V23 (Median GAN),1,1730.613686,3.548552,0.996051,0.423351,0.748521,0.995392,0.423351,0.996051,0.455503,0.995327,0.377954,0.275684,0.259956,0.933333,0.062780,0.117647,0.250559,0.315000,0.208264,0.250746,0.456090,0.997229,0.999007,0.998117,0.472449
1,V23 (Median GAN),2,1730.613686,3.505948,0.996782,0.454775,0.811550,0.996146,0.454775,0.996782,0.506652,0.996049,0.447916,0.401114,0.368153,0.956522,0.098655,0.178862,0.314093,0.480597,0.266116,0.342553,0.515670,0.997531,0.999555,0.998542,0.554828
2,V23 (Median GAN),3,1730.613686,3.495813,0.996163,0.587376,0.781258,0.996853,0.587376,0.996163,0.606438,0.996262,0.648786,0.488183,0.487484,0.982143,0.246637,0.394265,0.496624,0.363109,0.517355,0.426721,0.718422,0.998523,0.998135,0.998329,0.765416
3,V23 (Median GAN),4,1730.613686,3.493025,0.998486,0.823034,0.889039,0.998368,0.823034,0.998486,0.852782,0.998402,0.852647,0.771141,0.768127,0.878505,0.843049,0.860412,0.918126,0.789583,0.626446,0.698618,0.791311,0.999029,0.999607,0.999318,0.853214

In [ ]:
df_v23.to_csv("results_v23.csv", index=False)

## V_CDSMOTE

In [ ]:
df_v2 = run_experiment(
    base_path=base_path,
    train_file="train_median_cdsmote.parquet",
    val_file="val.parquet",
    test_prefix="test",
    version_name="V2 (Median CDSMOTE)"
)

df_v2

####################
Version: V2 (Median CDSMOTE)
####################
Loading train (GPU): /kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/train_median_cdsmote.parquet
Train samples: 5558987
Validation samples: 232452
Phase 1: 39 features
Phase 2: 39 features
Phase 3: 39 features
Phase 4: 39 features
Time-series shape: (5558987, 4, 39)
Static feature shape: (5558987, 23)
Classes: [0 1 2]
Epoch 1: train = 0.0347, val = 0.0233
Epoch 2: train = 0.0173, val = 0.0228
Epoch 3: train = 0.0145, val = 0.0207
Epoch 4: train = 0.0129, val = 0.0223
Epoch 5: train = 0.0119, val = 0.0201
Epoch 6: train = 0.0112, val = 0.0198
Epoch 7: train = 0.0107, val = 0.0188
Epoch 8: train = 0.0102, val = 0.0212
Epoch 9: train = 0.0098, val = 0.0189
Epoch 10: train = 0.0096, val = 0.0192
Epoch 11: train = 0.0093, val = 0.0214
Epoch 12: train = 0.0090, val = 0.0178
Epoch 13: train = 0.0089, val = 0.0217
Epoch 14: train = 0.0087, val = 0.0190
Epoch 15: train = 0.0086, val = 0.0199
Epoch 16: train = 0.0084, val = 0.0188
Epoch 17: train = 0.0083, val = 0.0196
Epoch 18: train = 0.0082, val = 0.0197
Epoch 19: train = 0.0080, val = 0.0209
Epoch 20: train = 0.0079, val = 0.0187
Epoch 21: train = 0.0079, val = 0.0200
Epoch 22: train = 0.0078, val = 0.0214

--- Test Phase 1: /kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/test_1.parquet ---

============================== V2 (Median CDSMOTE) - Phase 1 ==============================
              precision    recall  f1-score   support

   Excellent  0.9655172414 0.1255605381 0.2222222222       223
        Good  1.0000000000 0.0049586777 0.0098684211       605
     Average  0.9965708778 0.9999956827 0.9982803429    231625

    accuracy                      0.9965670480    232453
   macro avg  0.9873627064 0.3768382995 0.4101236621    232453
weighted avg  0.9965500119 0.9965670480 0.9949633275    232453

G-Mean per class (one-vs-rest):
  Excellent : 0.3543444616
  Good      : 0.0704178790
  Average   : 0.1934927696

TimeBuildModel         : 2734.5813692210
TimePredict            : 3.6004242170
Accuracy               : 0.9965670480
BalancedAcc            : 0.3768382995
Precision Macro        : 0.9873627064
Precision Weighted     : 0.9965500119
Recall Macro           : 0.3768382995
Recall Weighted        : 0.9965670480
F1-Score Macro         : 0.4101236621
F1-Score Weighted      : 0.9949633275
GMean                  : 0.1690146862
MCC                    : 0.1902706413
Kappa                  : 0.0719315684
Precision_Excellent    : 0.9655172414
Recall_Excellent       : 0.1255605381
F1-Score_Excellent     : 0.2222222222
G-Mean_Excellent       : 0.3543444616
Precision_Good         : 1.0000000000
Recall_Good            : 0.0049586777
F1-Score_Good          : 0.0098684211
G-Mean_Good            : 0.0704178790
Precision_Average      : 0.9965708778
Recall_Average         : 0.9999956827
F1-Score_Average       : 0.9982803429
G-Mean_Average         : 0.1934927696

--- Test Phase 2: /kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/test_2.parquet ---

============================== V2 (Median CDSMOTE) - Phase 2 ==============================
              precision    recall  f1-score   support

   Excellent  0.9375000000 0.2690582960 0.4181184669       223
        Good  0.9333333333 0.0462809917 0.0881889764       605
     Average  0.9968238803 0.9999827307 0.9984008069    231625

    accuracy                      0.9967993530    232453
   macro avg  0.9558857379 0.4384406728 0.5015694167    232453
weighted avg  0.9966017235 0.9967993530 0.9954751354    232453

G-Mean per class (one-vs-rest):
  Excellent : 0.5187038284
  Good      : 0.2151292460
  Average   : 0.3296873899

TimeBuildModel         : 2734.5813692210
TimePredict            : 3.6703675490
Accuracy               : 0.9967993530
BalancedAcc            : 0.4384406728
Precision Macro        : 0.9558857379
Precision Weighted     : 0.9966017235
Recall Macro           : 0.4384406728
Recall Weighted        : 0.9967993530
F1-Score Macro         : 0.5015694167
F1-Score Weighted      : 0.9954751354
GMean                  : 0.3325883876
MCC                    : 0.3186713548
Kappa                  : 0.1926432379
Precision_Excellent    : 0.9375000000
Recall_Excellent       : 0.2690582960
F1-Score_Excellent     : 0.4181184669
G-Mean_Excellent       : 0.5187038284
Precision_Good         : 0.9333333333
Recall_Good            : 0.0462809917
F1-Score_Good          : 0.0881889764
G-Mean_Good            : 0.2151292460
Precision_Average      : 0.9968238803
Recall_Average         : 0.9999827307
F1-Score_Average       : 0.9984008069
G-Mean_Average         : 0.3296873899

--- Test Phase 3: /kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/test_3.parquet ---

============================== V2 (Median CDSMOTE) - Phase 3 ==============================
              precision    recall  f1-score   support

   Excellent  0.5073313783 0.7757847534 0.6134751773       223
        Good  0.8362068966 0.3206611570 0.4635603345       605
     Average  0.9981110919 0.9992099298 0.9986602086    231625

    accuracy                      0.9972295475    232453
   macro avg  0.7805497889 0.6985519467 0.6918985735    232453
weighted avg  0.9972188861 0.9972295475 0.9968979957    232453

G-Mean per class (one-vs-rest):
  Excellent : 0.8804677930
  Good      : 0.5662231014
  Average   : 0.6860337880

TimeBuildModel         : 2734.5813692210
TimePredict            : 3.5390856210
Accuracy               : 0.9972295475
BalancedAcc            : 0.6985519467
Precision Macro        : 0.7805497889
Precision Weighted     : 0.9972188861
Recall Macro           : 0.6985519467
Recall Weighted        : 0.9972295475
F1-Score Macro         : 0.6918985735
F1-Score Weighted      : 0.9968979957
GMean                  : 0.6993300467
MCC                    : 0.5486480523
Kappa                  : 0.5393511479
Precision_Excellent    : 0.5073313783
Recall_Excellent       : 0.7757847534
F1-Score_Excellent     : 0.6134751773
G-Mean_Excellent       : 0.8804677930
Precision_Good         : 0.8362068966
Recall_Good            : 0.3206611570
F1-Score_Good          : 0.4635603345
G-Mean_Good            : 0.5662231014
Precision_Average      : 0.9981110919
Recall_Average         : 0.9992099298
F1-Score_Average       : 0.9986602086
G-Mean_Average         : 0.6860337880

--- Test Phase 4: /kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/test_4.parquet ---

============================== V2 (Median CDSMOTE) - Phase 4 ==============================
              precision    recall  f1-score   support

   Excellent  0.4361233480 0.8878923767 0.5849335303       223
        Good  0.4107744108 0.8066115702 0.5443390965       605
     Average  0.9995754102 0.9960626012 0.9978159140    231625

    accuracy                      0.9954657501    232453
   macro avg  0.6154910563 0.8968555160 0.7090295136    232453
weighted avg  0.9975024130 0.9954657501 0.9962395685    232453

G-Mean per class (one-vs-rest):
  Excellent : 0.9417609058
  Good      : 0.8967587373
  Average   : 0.9371078561

TimeBuildModel         : 2734.5813692210
TimePredict            : 3.5426549270
Accuracy               : 0.9954657501
BalancedAcc            : 0.8968555160
Precision Macro        : 0.6154910563
Precision Weighted     : 0.9975024130
Recall Macro           : 0.8968555160
Recall Weighted        : 0.9954657501
F1-Score Macro         : 0.7090295136
F1-Score Weighted      : 0.9962395685
GMean                  : 0.9249862661
MCC                    : 0.6057575783
Kappa                  : 0.5716533103
Precision_Excellent    : 0.4361233480
Recall_Excellent       : 0.8878923767
F1-Score_Excellent     : 0.5849335303
G-Mean_Excellent       : 0.9417609058
Precision_Good         : 0.4107744108
Recall_Good            : 0.8066115702
F1-Score_Good          : 0.5443390965
G-Mean_Good            : 0.8967587373
Precision_Average      : 0.9995754102
Recall_Average         : 0.9960626012
F1-Score_Average       : 0.9978159140
G-Mean_Average         : 0.9371078561

,Version,Phase,TimeBuildModel,TimePredict,Accuracy,BalancedAcc,Precision Macro,Precision Weighted,Recall Macro,Recall Weighted,F1-Score Macro,F1-Score Weighted,GMean,MCC,Kappa,Precision_Excellent,Recall_Excellent,F1-Score_Excellent,G-Mean_Excellent,Precision_Good,Recall_Good,F1-Score_Good,G-Mean_Good,Precision_Average,Recall_Average,F1-Score_Average,G-Mean_Average
0,V2 (Median CDSMOTE),1,2734.581369,3.600424,0.996567,0.376838,0.987363,0.996550,0.376838,0.996567,0.410124,0.994963,0.169015,0.190271,0.071932,0.965517,0.125561,0.222222,0.354344,1.000000,0.004959,0.009868,0.070418,0.996571,0.999996,0.998280,0.193493
1,V2 (Median CDSMOTE),2,2734.581369,3.670368,0.996799,0.438441,0.955886,0.996602,0.438441,0.996799,0.501569,0.995475,0.332588,0.318671,0.192643,0.937500,0.269058,0.418118,0.518704,0.933333,0.046281,0.088189,0.215129,0.996824,0.999983,0.998401,0.329687
2,V2 (Median CDSMOTE),3,2734.581369,3.539086,0.997230,0.698552,0.780550,0.997219,0.698552,0.997230,0.691899,0.996898,0.699330,0.548648,0.539351,0.507331,0.775785,0.613475,0.880468,0.836207,0.320661,0.463560,0.566223,0.998111,0.999210,0.998660,0.686034
3,V2 (Median CDSMOTE),4,2734.581369,3.542655,0.995466,0.896856,0.615491,0.997502,0.896856,0.995466,0.709030,0.996240,0.924986,0.605758,0.571653,0.436123,0.887892,0.584934,0.941761,0.410774,0.806612,0.544339,0.896759,0.999575,0.996063,0.997816,0.937108

In [ ]:
df_v2.to_csv("results_v2.csv", index=False)

## V_SMOTified GAN

In [ ]:
base_path_1 = "/kaggle/input/datasets/uyentran10/lo-smotifiedgan-test"

In [ ]:
df_v24 = run_experiment(
    base_path=base_path,
    train_file="train_median_smotified_gan.parquet",
    val_file="val.parquet",
    test_prefix="test",
    version_name="V24 (Median SMOTified GAN)"
)

df_v24

####################
Version: V24 (Median SMOTified GAN)
####################
Loading train (GPU): /kaggle/input/datasets/uyentran10/lo-smotifiedgan-test/train_median_smotified_gan.parquet
Train samples: 5558991
Validation samples: 232452
Phase 1: 39 features
Phase 2: 39 features
Phase 3: 39 features
Phase 4: 39 features
Time-series shape: (5558991, 4, 39)
Static feature shape: (5558991, 23)
Classes: [0 1 2]
Epoch 1: train = 0.0036, val = 0.0063
Epoch 2: train = 0.0021, val = 0.0052
Epoch 3: train = 0.0019, val = 0.0048
Epoch 4: train = 0.0018, val = 0.0050
Epoch 5: train = 0.0017, val = 0.0050
Epoch 6: train = 0.0016, val = 0.0051
Epoch 7: train = 0.0016, val = 0.0049
Epoch 8: train = 0.0015, val = 0.0051
Epoch 9: train = 0.0015, val = 0.0048
Epoch 10: train = 0.0014, val = 0.0050
Epoch 11: train = 0.0014, val = 0.0049
Epoch 12: train = 0.0014, val = 0.0048
Epoch 13: train = 0.0014, val = 0.0049

--- Test Phase 1: /kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/test_1.parquet ---

============================== V24 (Median SMOTified GAN) - Phase 1 ==============================
              precision    recall  f1-score   support

   Excellent  0.8518518519 0.1031390135 0.1840000000       223
        Good  0.0372016846 0.7884297521 0.0710508677       605
     Average  0.9993852571 0.9475186185 0.9727610592    231625

    accuracy                      0.9462945198    232453
   macro avg  0.6294795979 0.6130291280 0.4092706423    232453
weighted avg  0.9967394706 0.9462945198 0.9696575141    232453

G-Mean per class (one-vs-rest):
  Excellent : 0.3211498668
  Good      : 0.8639727708
  Average   : 0.8905233782

TimeBuildModel         : 1626.6882829050
TimePredict            : 3.3500283050
Accuracy               : 0.9462945198
BalancedAcc            : 0.6130291280
Precision Macro        : 0.6294795979
Precision Weighted     : 0.9967394706
Recall Macro           : 0.6130291280
Recall Weighted        : 0.9462945198
F1-Score Macro         : 0.4092706423
F1-Score Weighted      : 0.9696575141
GMean                  : 0.6275057488
MCC                    : 0.1759072483
Kappa                  : 0.0819126253
Precision_Excellent    : 0.8518518519
Recall_Excellent       : 0.1031390135
F1-Score_Excellent     : 0.1840000000
G-Mean_Excellent       : 0.3211498668
Precision_Good         : 0.0372016846
Recall_Good            : 0.7884297521
F1-Score_Good          : 0.0710508677
G-Mean_Good            : 0.8639727708
Precision_Average      : 0.9993852571
Recall_Average         : 0.9475186185
F1-Score_Average       : 0.9727610592
G-Mean_Average         : 0.8905233782

--- Test Phase 2: /kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/test_2.parquet ---

============================== V24 (Median SMOTified GAN) - Phase 2 ==============================
              precision    recall  f1-score   support

   Excellent  0.3361344538 0.1793721973 0.2339181287       223
        Good  0.0211348133 0.8859504132 0.0412847570       605
     Average  0.9996424654 0.8932498651 0.9434561945    231625

    accuracy                      0.8925460201    232453
   macro avg  0.4523039108 0.6528574919 0.4062196934    232453
weighted avg  0.9964592008 0.8925460201 0.9404274502    232453

G-Mean per class (one-vs-rest):
  Excellent : 0.4234515066
  Good      : 0.8894311378
  Average   : 0.9018970869

TimeBuildModel         : 1626.6882829050
TimePredict            : 3.5144245670
Accuracy               : 0.8925460201
BalancedAcc            : 0.6528574919
Precision Macro        : 0.4523039108
Precision Weighted     : 0.9964592008
Recall Macro           : 0.6528574919
Recall Weighted        : 0.8925460201
F1-Score Macro         : 0.4062196934
F1-Score Weighted      : 0.9404274502
GMean                  : 0.6977357871
MCC                    : 0.1354896042
Kappa                  : 0.0448592397
Precision_Excellent    : 0.3361344538
Recall_Excellent       : 0.1793721973
F1-Score_Excellent     : 0.2339181287
G-Mean_Excellent       : 0.4234515066
Precision_Good         : 0.0211348133
Recall_Good            : 0.8859504132
F1-Score_Good          : 0.0412847570
G-Mean_Good            : 0.8894311378
Precision_Average      : 0.9996424654
Recall_Average         : 0.8932498651
F1-Score_Average       : 0.9434561945
G-Mean_Average         : 0.9018970869

--- Test Phase 3: /kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/test_3.parquet ---

============================== V24 (Median SMOTified GAN) - Phase 3 ==============================
              precision    recall  f1-score   support

   Excellent  0.6369047619 0.4798206278 0.5473145780       223
        Good  0.0488492250 0.8595041322 0.0924444444       605
     Average  0.9996210070 0.9565288721 0.9776003000    231625

    accuracy                      0.9558190258    232453
   macro avg  0.5617916646 0.7652845440 0.5391197742    232453
weighted avg  0.9967984896 0.9558190258 0.9748837380    232453

G-Mean per class (one-vs-rest):
  Excellent : 0.6925998795
  Good      : 0.9066249794
  Average   : 0.9270866794

TimeBuildModel         : 1626.6882829050
TimePredict            : 3.5249957190
Accuracy               : 0.9558190258
BalancedAcc            : 0.7652845440
Precision Macro        : 0.5617916646
Precision Weighted     : 0.9967984896
Recall Macro           : 0.7652845440
Recall Weighted        : 0.9558190258
F1-Score Macro         : 0.5391197742
F1-Score Weighted      : 0.9748837380
GMean                  : 0.8349814189
MCC                    : 0.2234953871
Kappa                  : 0.1127136461
Precision_Excellent    : 0.6369047619
Recall_Excellent       : 0.4798206278
F1-Score_Excellent     : 0.5473145780
G-Mean_Excellent       : 0.6925998795
Precision_Good         : 0.0488492250
Recall_Good            : 0.8595041322
F1-Score_Good          : 0.0924444444
G-Mean_Good            : 0.9066249794
Precision_Average      : 0.9996210070
Recall_Average         : 0.9565288721
F1-Score_Average       : 0.9776003000
G-Mean_Average         : 0.9270866794

--- Test Phase 4: /kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/test_4.parquet ---

============================== V24 (Median SMOTified GAN) - Phase 4 ==============================
              precision    recall  f1-score   support

   Excellent  0.8651162791 0.8340807175 0.8493150685       223
        Good  0.7719298246 0.6545454545 0.7084078712       605
     Average  0.9990764915 0.9995078251 0.9992921118    231625

    accuracy                      0.9984512998    232453
   macro avg  0.8787075317 0.8293779991 0.8523383505    232453
weighted avg  0.9983567897 0.9984512998 0.9983911561    232453

G-Mean per class (one-vs-rest):
  Excellent : 0.9132231713
  Good      : 0.8088356719
  Average   : 0.8609186509

TimeBuildModel         : 1626.6882829050
TimePredict            : 3.5204929770
Accuracy               : 0.9984512998
BalancedAcc            : 0.8293779991
Precision Macro        : 0.8787075317
Precision Weighted     : 0.9983567897
Recall Macro           : 0.8293779991
Recall Weighted        : 0.9984512998
F1-Score Macro         : 0.8523383505
F1-Score Weighted      : 0.9983911561
GMean                  : 0.8599366231
MCC                    : 0.7696224596
Kappa                  : 0.7680211223
Precision_Excellent    : 0.8651162791
Recall_Excellent       : 0.8340807175
F1-Score_Excellent     : 0.8493150685
G-Mean_Excellent       : 0.9132231713
Precision_Good         : 0.7719298246
Recall_Good            : 0.6545454545
F1-Score_Good          : 0.7084078712
G-Mean_Good            : 0.8088356719
Precision_Average      : 0.9990764915
Recall_Average         : 0.9995078251
F1-Score_Average       : 0.9992921118
G-Mean_Average         : 0.8609186509

,Version,Phase,TimeBuildModel,TimePredict,Accuracy,BalancedAcc,Precision Macro,Precision Weighted,Recall Macro,Recall Weighted,F1-Score Macro,F1-Score Weighted,GMean,MCC,Kappa,Precision_Excellent,Recall_Excellent,F1-Score_Excellent,G-Mean_Excellent,Precision_Good,Recall_Good,F1-Score_Good,G-Mean_Good,Precision_Average,Recall_Average,F1-Score_Average,G-Mean_Average
0,V24 (Median SMOTified GAN),1,1626.688283,3.350028,0.946295,0.613029,0.629480,0.996739,0.613029,0.946295,0.409271,0.969658,0.627506,0.175907,0.081913,0.851852,0.103139,0.184000,0.321150,0.037202,0.788430,0.071051,0.863973,0.999385,0.947519,0.972761,0.890523
1,V24 (Median SMOTified GAN),2,1626.688283,3.514425,0.892546,0.652857,0.452304,0.996459,0.652857,0.892546,0.406220,0.940427,0.697736,0.135490,0.044859,0.336134,0.179372,0.233918,0.423452,0.021135,0.885950,0.041285,0.889431,0.999642,0.893250,0.943456,0.901897
2,V24 (Median SMOTified GAN),3,1626.688283,3.524996,0.955819,0.765285,0.561792,0.996798,0.765285,0.955819,0.539120,0.974884,0.834981,0.223495,0.112714,0.636905,0.479821,0.547315,0.692600,0.048849,0.859504,0.092444,0.906625,0.999621,0.956529,0.977600,0.927087
3,V24 (Median SMOTified GAN),4,1626.688283,3.520493,0.998451,0.829378,0.878708,0.998357,0.829378,0.998451,0.852338,0.998391,0.859937,0.769622,0.768021,0.865116,0.834081,0.849315,0.913223,0.771930,0.654545,0.708408,0.808836,0.999076,0.999508,0.999292,0.860919

In [ ]:
df_v24.to_csv("results_v24.csv", index=False)

## V_CDSMOTified GAN

In [ ]:
base_path_1 = "/kaggle/input/datasets/hngliththu/cdsmote-gan"

In [ ]:
base_path = "/kaggle/input/datasets/anhtran10/lo-dataset/Median/Median"

In [ ]:
df_v13 = run_experiment(
    base_path=base_path,
    train_file="train_median_cdsmote_gan.parquet",
    val_file="val.parquet",
    test_prefix="test",
    version_name="V13 (Median CDSMOTified GAN)"
)
df_v13

####################
Version: V13 (Median CDSMOTified GAN)
####################
Loading train (GPU): /kaggle/input/datasets/hngliththu/cdsmote-gan/train_median_cdsmote_gan.parquet
Train samples: 5558987
Validation samples: 232452
Phase 1: 39 features
Phase 2: 39 features
Phase 3: 39 features
Phase 4: 39 features
Time-series shape: (5558987, 4, 39)
Static feature shape: (5558987, 23)
Classes: [0 1 2]
Epoch 1: train = 0.0035, val = 0.0057
Epoch 2: train = 0.0020, val = 0.0050
Epoch 3: train = 0.0019, val = 0.0050
Epoch 4: train = 0.0017, val = 0.0047
Epoch 5: train = 0.0017, val = 0.0054
Epoch 6: train = 0.0016, val = 0.0045
Epoch 7: train = 0.0015, val = 0.0046
Epoch 8: train = 0.0015, val = 0.0047
Epoch 9: train = 0.0015, val = 0.0053
Epoch 10: train = 0.0014, val = 0.0052
Epoch 11: train = 0.0014, val = 0.0049
Epoch 12: train = 0.0013, val = 0.0051
Epoch 13: train = 0.0013, val = 0.0050
Epoch 14: train = 0.0013, val = 0.0057
Epoch 15: train = 0.0013, val = 0.0055
Epoch 16: train = 0.0012, val = 0.0058

--- Test Phase 1: /kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/test_1.parquet ---

============================== V13 (Median CDSMOTified GAN) - Phase 1 ==============================
              precision    recall  f1-score   support

   Excellent  0.9375000000 0.1345291480 0.2352941176       223
        Good  0.2566666667 0.3818181818 0.3069767442       605
     Average  0.9977583027 0.9973103076 0.9975342549    231625

    accuracy                      0.9948806856    232453
   macro avg  0.7306416565 0.5045525458 0.5132683722    232453
weighted avg  0.9957716730 0.9948806856 0.9950057143    232453

G-Mean per class (one-vs-rest):
  Excellent : 0.3667805739
  Good      : 0.6170222372
  Average   : 0.6100693762

TimeBuildModel         : 1930.4547073270
TimePredict            : 3.4563313330
Accuracy               : 0.9948806856
BalancedAcc            : 0.5045525458
Precision Macro        : 0.7306416565
Precision Weighted     : 0.9957716730
Recall Macro           : 0.5045525458
Recall Weighted        : 0.9948806856
F1-Score Macro         : 0.5132683722
F1-Score Weighted      : 0.9950057143
GMean                  : 0.5168471458
MCC                    : 0.3222759924
Kappa                  : 0.3216695065
Precision_Excellent    : 0.9375000000
Recall_Excellent       : 0.1345291480
F1-Score_Excellent     : 0.2352941176
G-Mean_Excellent       : 0.3667805739
Precision_Good         : 0.2566666667
Recall_Good            : 0.3818181818
F1-Score_Good          : 0.3069767442
G-Mean_Good            : 0.6170222372
Precision_Average      : 0.9977583027
Recall_Average         : 0.9973103076
F1-Score_Average       : 0.9975342549
G-Mean_Average         : 0.6100693762

--- Test Phase 2: /kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/test_2.parquet ---

============================== V13 (Median CDSMOTified GAN) - Phase 2 ==============================
              precision    recall  f1-score   support

   Excellent  0.9516129032 0.2645739910 0.4140350877       223
        Good  0.4078947368 0.4611570248 0.4328937161       605
     Average  0.9980406289 0.9983939557 0.9982172611    231625

    accuracy                      0.9962917235    232453
   macro avg  0.7858494230 0.5747083239 0.6150486883    232453
weighted avg  0.9964601303 0.9962917235 0.9961854810    232453

G-Mean per class (one-vs-rest):
  Excellent : 0.5143642418
  Good      : 0.6784920486
  Average   : 0.6715395638

TimeBuildModel         : 1930.4547073270
TimePredict            : 3.3386819220
Accuracy               : 0.9962917235
BalancedAcc            : 0.5747083239
Precision Macro        : 0.7858494230
Precision Weighted     : 0.9964601303
Recall Macro           : 0.5747083239
Recall Weighted        : 0.9962917235
F1-Score Macro         : 0.6150486883
F1-Score Weighted      : 0.9961854810
GMean                  : 0.6165415907
MCC                    : 0.4514198145
Kappa                  : 0.4507815639
Precision_Excellent    : 0.9516129032
Recall_Excellent       : 0.2645739910
F1-Score_Excellent     : 0.4140350877
G-Mean_Excellent       : 0.5143642418
Precision_Good         : 0.4078947368
Recall_Good            : 0.4611570248
F1-Score_Good          : 0.4328937161
G-Mean_Good            : 0.6784920486
Precision_Average      : 0.9980406289
Recall_Average         : 0.9983939557
F1-Score_Average       : 0.9982172611
G-Mean_Average         : 0.6715395638

--- Test Phase 3: /kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/test_3.parquet ---

============================== V13 (Median CDSMOTified GAN) - Phase 3 ==============================
              precision    recall  f1-score   support

   Excellent  0.8897058824 0.5426008969 0.6740947075       223
        Good  0.4741896759 0.6528925620 0.5493741307       605
     Average  0.9989070519 0.9982989746 0.9986029207    231625

    accuracy                      0.9969628269    232453
   macro avg  0.7876008700 0.7312641445 0.7406905863    232453
weighted avg  0.9974366219 0.9969628269 0.9971224117    232453

G-Mean per class (one-vs-rest):
  Excellent : 0.7365906934
  Good      : 0.8072540726
  Average   : 0.8326242711

TimeBuildModel         : 1930.4547073270
TimePredict            : 3.4499169050
Accuracy               : 0.9969628269
BalancedAcc            : 0.7312641445
Precision Macro        : 0.7876008700
Precision Weighted     : 0.9974366219
Recall Macro           : 0.7312641445
Recall Weighted        : 0.9969628269
F1-Score Macro         : 0.7406905863
F1-Score Weighted      : 0.9971224117
GMean                  : 0.7910947691
MCC                    : 0.6077742709
Kappa                  : 0.6058618092
Precision_Excellent    : 0.8897058824
Recall_Excellent       : 0.5426008969
F1-Score_Excellent     : 0.6740947075
G-Mean_Excellent       : 0.7365906934
Precision_Good         : 0.4741896759
Recall_Good            : 0.6528925620
F1-Score_Good          : 0.5493741307
G-Mean_Good            : 0.8072540726
Precision_Average      : 0.9989070519
Recall_Average         : 0.9982989746
F1-Score_Average       : 0.9986029207
G-Mean_Average         : 0.8326242711

--- Test Phase 4: /kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/test_4.parquet ---

============================== V13 (Median CDSMOTified GAN) - Phase 4 ==============================
              precision    recall  f1-score   support

   Excellent  0.8250000000 0.8878923767 0.8552915767       223
        Good  0.7670682731 0.6314049587 0.6926563917       605
     Average  0.9990807673 0.9994689692 0.9992748306    231625

    accuracy                      0.9984039784    232453
   macro avg  0.8637163468 0.8395887682 0.8490742663    232453
weighted avg  0.9983099123 0.9984039784 0.9983386739    232453

G-Mean per class (one-vs-rest):
  Excellent : 0.9421952010
  Good      : 0.7944111336
  Average   : 0.8616026916

TimeBuildModel         : 1930.4547073270
TimePredict            : 3.4023587950
Accuracy               : 0.9984039784
BalancedAcc            : 0.8395887682
Precision Macro        : 0.8637163468
Precision Weighted     : 0.9983099123
Recall Macro           : 0.8395887682
Recall Weighted        : 0.9984039784
F1-Score Macro         : 0.8490742663
F1-Score Weighted      : 0.9983386739
GMean                  : 0.8639681892
MCC                    : 0.7637351673
Kappa                  : 0.7624604026
Precision_Excellent    : 0.8250000000
Recall_Excellent       : 0.8878923767
F1-Score_Excellent     : 0.8552915767
G-Mean_Excellent       : 0.9421952010
Precision_Good         : 0.7670682731
Recall_Good            : 0.6314049587
F1-Score_Good          : 0.6926563917
G-Mean_Good            : 0.7944111336
Precision_Average      : 0.9990807673
Recall_Average         : 0.9994689692
F1-Score_Average       : 0.9992748306
G-Mean_Average         : 0.8616026916

,Version,Phase,TimeBuildModel,TimePredict,Accuracy,BalancedAcc,Precision Macro,Precision Weighted,Recall Macro,Recall Weighted,F1-Score Macro,F1-Score Weighted,GMean,MCC,Kappa,Precision_Excellent,Recall_Excellent,F1-Score_Excellent,G-Mean_Excellent,Precision_Good,Recall_Good,F1-Score_Good,G-Mean_Good,Precision_Average,Recall_Average,F1-Score_Average,G-Mean_Average
0,V13 (Median CDSMOTified GAN),1,1930.454707,3.456331,0.994881,0.504553,0.730642,0.995772,0.504553,0.994881,0.513268,0.995006,0.516847,0.322276,0.321670,0.937500,0.134529,0.235294,0.366781,0.256667,0.381818,0.306977,0.617022,0.997758,0.997310,0.997534,0.610069
1,V13 (Median CDSMOTified GAN),2,1930.454707,3.338682,0.996292,0.574708,0.785849,0.996460,0.574708,0.996292,0.615049,0.996185,0.616542,0.451420,0.450782,0.951613,0.264574,0.414035,0.514364,0.407895,0.461157,0.432894,0.678492,0.998041,0.998394,0.998217,0.671540
2,V13 (Median CDSMOTified GAN),3,1930.454707,3.449917,0.996963,0.731264,0.787601,0.997437,0.731264,0.996963,0.740691,0.997122,0.791095,0.607774,0.605862,0.889706,0.542601,0.674095,0.736591,0.474190,0.652893,0.549374,0.807254,0.998907,0.998299,0.998603,0.832624
3,V13 (Median CDSMOTified GAN),4,1930.454707,3.402359,0.998404,0.839589,0.863716,0.998310,0.839589,0.998404,0.849074,0.998339,0.863968,0.763735,0.762460,0.825000,0.887892,0.855292,0.942195,0.767068,0.631405,0.692656,0.794411,0.999081,0.999469,0.999275,0.861603

In [ ]:
df_v13.to_csv("results_v13.csv", index=False)